// import { Panaverse, Todo, Steps, LandingPage, DarkMode, Testimonial, CartSection, CryptoPrices, FoodWeb, NavbarTemp, PricingUi, TopLabel, BooksWeb, NumberGuessing, Calculator, ScrollAnimation, VideoPlayer, UniversityManagmentSystem, QuizApp } from "@/components/assets/Images"

// export interface CarouselCardDataType {
//     images: any,
//     alt: string,
//     subHeading: string,
//     heading: string,
//     btn: string,
//     link: string,
//     content: string,
//     github: string,
// }

// export const CarouselCardData: Array<CarouselCardDataType> = [
//     {
//         images: Panaverse,
//         alt: "Panaverse dao",
//         subHeading: "Website",
//         heading: "Panaverse Dao Website",
//         btn: "Preview",
//         link: "https://panaverse-dao-nine.vercel.app/",
//         content: "This is Panaverse Dao (Decentralize AutoNumas Organizaioin) local website that i made as assignment and this is my work.",
//         github: "https://github.com/basitgggg/Panaverse-dao",
//     },
//     {
//         images: Todo,
//         alt: "todo",
//         subHeading: "App",
//         heading: "Todo App",
//         btn: "Preview",
//         link: "https://todo-one-ochre.vercel.app/",
//         content: "This is Todo local app that i made as assignment for PIAIC projects and this is my work and experience in front of you.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/2Todo%20app",
//     },
//     {
//         images: Steps,
//         alt: "steps",
//         subHeading: "App",
//         heading: "Steps App",
//         btn: "Preview",
//         link: "https://7steps.vercel.app/",
//         content: "Steps component like Youtube and Faceboog local app can be assigned many step whatever you want that i made as assignment and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/7steps",
//     },
//     {
//         images: LandingPage,
//         alt: "landing page",
//         subHeading: "Website",
//         heading: "Landing Page",
//         btn: "Preview",
//         link: "https://5landin-page.vercel.app/",
//         content: "Landing Page local Design or Templete that i made as assignment on Css which is Chakra UI and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/5landin-page",
//     },
//     {
//         images: DarkMode,
//         alt: "dark mode",
//         subHeading: "Toggler",
//         heading: "Dark and Light Mode",
//         btn: "Preview",
//         link: "https://switcher-sand.vercel.app/",
//         content: "Dark Mode Toggler local app which allow user to toggle between dark and light mode.",
//         github: "https://github.com/basitgggg/Dark-mode-Switcher",
//     },
//     {
//         images: Testimonial,
//         alt: "testimonials",
//         subHeading: "Website",
//         heading: "Testimonials",
//         btn: "Preview",
//         link: "https://8testimonials.vercel.app/",
//         content: "This is Testimonials local Design textimonial are essential part of website to get user focus and i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/8testimonials",
//     },
//     {
//         images: BooksWeb,
//         alt: "e-commerce",
//         subHeading: "E-commerce Website",
//         heading: "Books E-commerce",
//         btn: "Preview",
//         link: "https://booksweb-basitgggg.vercel.app/",
//         content: "This is Books Website local Design and built for e-commerce.Selling section are essential part of e-commerce website to place order and i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/apis/tree/master/booksweb",
//     },
//     {
//         images: CartSection,
//         alt: "e-commerce",
//         subHeading: "E-commerce Website",
//         heading: "E-commerce",
//         btn: "Preview",
//         link: "https://1details-cart-basitgggg.vercel.app/",
//         content: "This is Cart section local Design for e-commerce are essential part of e-commerce website to place order and i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/1details-cart",
//     },
//     {
//         images: CryptoPrices,
//         alt: "crypto",
//         subHeading: "App",
//         heading: "CryptoPrices",
//         btn: "Preview",
//         link: "https://cryptoprices-tau.vercel.app/",
//         content: "This is Crypto updated Prices localy Design website to get grade and i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/apis/tree/master/cryptocurrencyprice",
//     },
//     {
//         images: FoodWeb,
//         alt: "FoodWeb",
//         subHeading: "Website",
//         heading: "FoodWeb",
//         btn: "Preview",
//         link: "https://gericht-basitgggg.vercel.app/",
//         content: "This is Food Website local Design to get user grade in study and i made as assignment for my Piaic projects and this is my work.",
//         github: "/",
//     },
//     {
//         images: NavbarTemp,
//         alt: "NavbarT",
//         subHeading: "Website",
//         heading: "Navbar",
//         btn: "Preview",
//         link: "https://4navbar.vercel.app/",
//         content: "This is Navbar local Design for website are essential part of website to navigate and i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/4navbar",
//     },
//     {
//         images: PricingUi,
//         alt: "Pricing Ui",
//         subHeading: "Website",
//         heading: "Pricing Ui",
//         btn: "Preview",
//         link: "https://next-js-styling-projects.vercel.app/",
//         content: "This is Pricing Ui local Design for a paid things on website are essential part of selling and i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/0pricing-ui",
//     },
//     {
//         images: TopLabel,
//         alt: "Toplabel",
//         subHeading: "Website",
//         heading: "Toplabel",
//         btn: "Preview",
//         link: "https://2top-bar.vercel.app/",
//         content: "This is Toplabel local Design for a website to get user focus and to show note i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/Next.js_styling_projects/tree/main/3top-bar",
//     },
//     {
//         images: NumberGuessing,
//         alt: "Number-Guessing Game Project",
//         subHeading: "Venilla Javascript Game",
//         heading: "Number-Guessing Game Project",
//         btn: "Preview",
//         link: "https://venerable-bonbon-c5e48e.netlify.app/",
//         content: "This is NumberGuessing Game for kids to get focus and to show i made as assignment for my Piaic projects and this is my work.",
//         github: "https://github.com/basitgggg/JavaScript-Projects/tree/master/Buli%20A%20game%20using%20js%20html%20css",
//     },
//     {
//         images: Calculator,
//         alt: "Calculator Project",
//         subHeading: "Venilla Javascript Calculation App",
//         heading: "Calculator Project",
//         btn: "Preview",
//         link: "https://silver-tanuki-8ab16e.netlify.app/",
//         content: "This is Calculator App for calculation of any math expresion like plus, substract, divide, multiply etc. i made it as assignment for my Piaic projects.",
//         github: "https://github.com/basitgggg/JavaScript-Projects/tree/master/Calculator",
//     },
//     {
//         images: QuizApp,
//         alt: "Quiz App",
//         subHeading: "Venilla Javascript Testing App",
//         heading: "Quiz App",
//         btn: "Preview",
//         link: "https://calm-meerkat-adf623.netlify.app/",
//         content: "This is Quiz App local Design for taking tests online at home to provide facility to student and to show results i made as assignment for my Piaic projects.",
//         github: "/",
//     },
//     {
//         images: ScrollAnimation,
//         alt: "Fade Animation on Scroll",
//         subHeading: "Venilla Javascript Artical",
//         heading: "Fade Animation on Scroll",
//         btn: "Preview",
//         link: "https://legendary-cheesecake-93307a.netlify.app/",
//         content: "This is app to show you how is fade in and fade out animation work in venella javascrip to get user focus. i made as assignment for my Piaic projects.",
//         github: "/",
//     },
//     {
//         images: VideoPlayer,
//         alt: "Video Player",
//         subHeading: "Venilla Javascript Video Player app",
//         heading: "Video Player",
//         btn: "Preview",
//         link: "https://aquamarine-figolla-7f033e.netlify.app/",
//         content: "It is custom build software to provide features to user.This is Video player provide user good streaming to get user focus i made as assignment for my Piaic projects.",
//         github: "/",
//     },
//     {
//         images: UniversityManagmentSystem,
//         alt: "University-Management-System",
//         subHeading: "Venilla Javascript U-M-S",
//         heading: "University-Management-System",
//         btn: "Preview",
//         link: "https://glittery-strudel-96dd8f.netlify.app/",
//         content: "This is University-Management-System build with typescript classes and converted into ui for interaction of user. I made as assignment for my Piaic projects.",
//         github: "/",
//     },
// ];









// Fetching data from api of contentfull for carousel

export async function getCarouselDataOfContentfullApi() {
    let manResponse = await fetch(`https://cdn.contentful.com/spaces/8ct6eyn41e88/environments/master/entries?access_token=CLDiH_AooWoxIxPEYbSbRRTqDfHp3t2uI56RZhjhZGk`);
    let responseToJson = await manResponse.json();
    return responseToJson;
}